import type { SeoPageConfig } from "@/lib/seo-pages/types";

const L = ["launcher-minecraft", "minecraft-launcher", "skachat-launcher-minecraft"];
const M = ["launcher-s-modami", "fabric-launcher", "forge-launcher", "modrinth-launcher"];
const S = ["minecraft-server", "minecraft-servers", "server-maincraft-dlya-druzei"];
const D = ["dopamine", "dopamine-launcher"];

/** Дополнительные SEO-страницы под расширенный набор поисковых запросов */
export const SEO_PAGES_EXTRA: SeoPageConfig[] = [
  {
    slug: "skachat-maincraft",
    title: "Скачать майнкрафт на ПК — через лаунчер dopamine",
    description:
      "Скачать майнкрафт на компьютер: dopamine — Minecraft launcher для Windows. Версии, моды Modrinth, Fabric, Forge, сервер для друзей. Бесплатный лаунчер.",
    keywords: ["скачать майнкрафт", "скачать minecraft", "майнкрафт скачать на пк", "minecraft скачать windows", "скачать майнкрафт на компьютер"],
    h1: "Скачать майнкрафт на ПК",
    subtitle: "dopamine — лаунчер для загрузки Minecraft, модов и игры с друзьями на Windows",
    tag: "скачать майнкрафт",
    sections: [
      {
        h2: "Как скачать майнкрафт через dopamine",
        paragraphs: [
          "Чтобы скачать майнкрафт на ПК, нужен надёжный лаунчер. dopamine скачивает нужную версию Minecraft, Java и моды — вы выбираете профиль и нажимаете «Играть».",
          "Скачайте установщик dopamine с официального сайта www.dopamine.cfd — актуальный лаунчер с автообновлениями.",
        ],
      },
      {
        h2: "Что входит",
        list: ["Vanilla и модовые версии Minecraft", "Modrinth — моды и modpack'и", "Локальный сервер для друзей", "RU/EN интерфейс, тёмная тема"],
        paragraphs: [],
      },
    ],
    faq: [{ q: "Скачать майнкрафт бесплатно через dopamine?", a: "Лаунчер dopamine бесплатен. Управление установками Minecraft на Windows — через профили в программе." }],
    relatedSlugs: [...L, "maincraft-na-pk"],
  },
  {
    slug: "maincraft-na-pk",
    title: "Майнкрафт на ПК — лаунчер для Windows | dopamine",
    description:
      "Майнкрафт на компьютер: dopamine Minecraft launcher для Windows 10/11. Моды, серверы, Fabric, Forge. Скачать лаунчер бесплатно.",
    keywords: ["майнкрафт на пк", "майнкрафт на компьютер", "minecraft на пк", "minecraft pc", "майнкрафт windows", "игра майнкрафт на пк"],
    h1: "Майнкрафт на ПК — dopamine",
    subtitle: "Запускайте Minecraft на компьютере: моды, версии и серверы для друзей",
    tag: "майнкрафт на пк",
    sections: [
      {
        h2: "Майнкрафт на компьютере через один лаунчер",
        paragraphs: [
          "Майнкрафт на ПК удобнее запускать через dopamine: несколько установок, Modrinth, настройка RAM и локальный мультиплеер. Лаунчер работает на Windows 10 и 11 (64-bit).",
        ],
      },
      {
        h2: "Системные требования",
        list: ["Windows 10/11 64-bit", "от 4 GB RAM (8+ для modpack'ов)", "интернет для первой загрузки", "Java — Temurin автоматически"],
        paragraphs: [],
      },
    ],
    faq: [{ q: "Подходит ли для слабого ПК?", a: "Для vanilla хватит 4 GB RAM. Тяжёлые modpack'и — от 8 GB с настройкой профиля." }],
    relatedSlugs: ["skachat-maincraft", "launcher-minecraft", "minecraft"],
  },
  {
    slug: "luchshiy-launcher-maincraft",
    title: "Лучший лаунчер майнкрафт 2026 — dopamine для Windows",
    description:
      "Лучший лаунчер майнкрафт: dopamine — Modrinth, Fabric, Forge, серверы для друзей, без рекламы. Бесплатный Minecraft launcher для Windows.",
    keywords: ["лучший лаунчер майнкрафт", "лучший лаунчер minecraft", "best minecraft launcher", "топ лаунчеров майнкрафт", "какой лаунчер майнкрафт лучше"],
    h1: "Лучший лаунчер майнкрафт",
    subtitle: "dopamine — Modrinth, серверы и единый аккаунт",
    tag: "лучший лаунчер",
    sections: [
      {
        h2: "Почему dopamine в топе лаунчеров",
        paragraphs: [
          "Искать «лучший лаунчер майнкрафт» — значит сравнивать моды, серверы и UX. dopamine: Modrinth из коробки, локальные серверы с туннелем, Fabric/Forge/NeoForge, без рекламы.",
        ],
      },
      {
        h2: "Преимущества",
        list: ["Modrinth и modpack'и", "Сервер для друзей без Hamachi", "Аккаунт dopamine.cfd", "Автообновления"],
        paragraphs: [],
      },
    ],
    faq: [{ q: "dopamine лучше официального лаунчера?", a: "Для modpack'ов и локальных серверов — удобнее." }],
    relatedSlugs: ["launcher-minecraft", "best-minecraft-launcher", "free-minecraft-launcher"],
  },
  {
    slug: "maincraft-s-modami",
    title: "Майнкрафт с модами — Fabric, Forge | dopamine",
    description:
      "Майнкрафт с модами: dopamine — Modrinth, Fabric, Forge, NeoForge. Установка modpack'ов на Windows бесплатно.",
    keywords: ["майнкрафт с модами", "minecraft с модами", "майнкрафт моды", "modpack майнкрафт", "сборки майнкрафт"],
    h1: "Майнкрафт с модами",
    subtitle: "Modrinth, Fabric и Forge в dopamine launcher",
    tag: "моды",
    sections: [
      {
        h2: "Майнкрафт с модами через dopamine",
        paragraphs: [
          "dopamine подбирает Fabric или Forge, скачивает моды с Modrinth и запускает сборку в один клик — без ручного копирования jar.",
        ],
      },
      {
        h2: "Modpack'и",
        list: ["Поиск Modrinth", "Modpack одной кнопкой", "Несколько сборок", "Обновление модов"],
        paragraphs: [],
      },
    ],
    faq: [{ q: "Shaders?", a: "Через Iris/Oculus на Fabric — моды из Modrinth." }],
    relatedSlugs: M,
  },
  {
    slug: "server-maincraft-dlya-druzei",
    title: "Сервер майнкрафт для друзей — без Hamachi | dopamine",
    description:
      "Сервер майнкрафт для друзей в dopamine. Туннель, modpack'и, RAM. Альтернатива Hamachi.",
    keywords: ["сервер майнкрафт для друзей", "майнкрафт с друзьями", "играть с друзьями майнкрафт", "локальный сервер для друзей"],
    h1: "Сервер майнкрафт для друзей",
    subtitle: "Мультиплеер без Hamachi — dopamine",
    tag: "мультиплеер",
    sections: [
      {
        h2: "Играть с друзьями",
        paragraphs: [
          "Создайте сервер за пару кликов — друзья подключаются по ссылке-туннелю из любой сети.",
        ],
      },
      {
        h2: "Без VPN",
        list: ["Встроенный туннель", "Vanilla и моды", "Настройка JVM", "Один лаунчер"],
        paragraphs: [],
      },
    ],
    faq: [{ q: "Сколько игроков?", a: "Обычно 3–8 на vanilla, зависит от RAM." }],
    relatedSlugs: S,
  },
  {
    slug: "fabric-launcher",
    title: "Fabric Launcher — Minecraft mods | dopamine",
    description: "Fabric launcher for Minecraft on Windows. Modrinth mods and modpacks. Free download.",
    keywords: ["fabric launcher", "minecraft fabric launcher", "fabric minecraft", "fabric mod launcher"],
    h1: "Fabric Launcher — dopamine",
    subtitle: "Fabric mods and modpacks on Windows",
    tag: "fabric",
    sections: [{ h2: "Fabric launcher", paragraphs: ["dopamine installs Fabric loader, Modrinth mods and launches modded profiles automatically."], list: ["One-click Fabric", "Modrinth search", "Modpacks", "Friend servers"], ordered: false }],
    faq: [{ q: "Fabric vs Forge?", a: "Both supported in separate profiles." }],
    relatedSlugs: ["forge-launcher", "neoforge-launcher", "modrinth-launcher"],
  },
  {
    slug: "forge-launcher",
    title: "Forge Launcher — Minecraft Forge | dopamine",
    description: "Forge launcher for Minecraft Windows. Modrinth forge modpacks. Free.",
    keywords: ["forge launcher", "minecraft forge launcher", "forge modpack launcher"],
    h1: "Forge Launcher — dopamine",
    subtitle: "Forge mods and modpacks",
    tag: "forge",
    sections: [{ h2: "Forge without manual setup", paragraphs: ["dopamine matches Forge to your Minecraft version and installs Modrinth mods."] }],
    faq: [{ q: "NeoForge?", a: "Supported — see neoforge-launcher." }],
    relatedSlugs: ["fabric-launcher", "neoforge-launcher"],
  },
  {
    slug: "neoforge-launcher",
    title: "NeoForge Launcher — Minecraft | dopamine",
    description: "NeoForge launcher for Minecraft Windows. Modrinth neoforge modpacks.",
    keywords: ["neoforge launcher", "minecraft neoforge", "neoforge modpack"],
    h1: "NeoForge Launcher",
    subtitle: "NeoForge modpacks via dopamine",
    tag: "neoforge",
    sections: [{ h2: "NeoForge support", paragraphs: ["Run NeoForge modpacks alongside Fabric and vanilla in one launcher."] }],
    faq: [],
    relatedSlugs: ["forge-launcher", "fabric-launcher"],
  },
  {
    slug: "modrinth-launcher",
    title: "Modrinth Launcher — modpacks | dopamine",
    description: "Modrinth launcher: modpacks and mods in dopamine. Fabric, Forge, NeoForge.",
    keywords: ["modrinth launcher", "modrinth modpack", "modrinth minecraft", "modrinth майнкрафт"],
    h1: "Modrinth Launcher — dopamine",
    subtitle: "Modrinth catalog inside the launcher",
    tag: "modrinth",
    sections: [
      { h2: "Built-in Modrinth", paragraphs: ["Search, install and update modpacks without a separate app."] },
      { h2: "Modrinth майнкрафт", paragraphs: ["dopamine — лаунчер с Modrinth, RU/EN и серверами для друзей."] },
    ],
    faq: [{ q: "Отдельное приложение Modrinth?", a: "Не нужно — всё в dopamine." }],
    relatedSlugs: ["minecraft-modpack-launcher", "launcher-s-modami"],
  },
  {
    slug: "hamachi-alternativa-maincraft",
    title: "Альтернатива Hamachi для майнкрафт | dopamine",
    description: "Альтернатива Hamachi: локальный сервер с туннелем в dopamine. Без VPN.",
    keywords: ["hamachi альтернатива майнкрафт", "хамachi майнкрафт", "играть без hamachi", "туннель майнкрафт"],
    h1: "Альтернатива Hamachi для майнкрафт",
    subtitle: "Сервер для друзей без Hamachi",
    tag: "без hamachi",
    sections: [{ h2: "Без Hamachi", paragraphs: ["dopamine — встроенный туннель вместо VPN-клиента."] }],
    faq: [{ q: "Hamachi нужен?", a: "Нет." }],
    relatedSlugs: ["hamachi-alternative-minecraft", ...S],
  },
  {
    slug: "hamachi-alternative-minecraft",
    title: "Hamachi Alternative Minecraft — dopamine",
    description: "Hamachi alternative: local server with tunnel. Play with friends free.",
    keywords: ["hamachi alternative minecraft", "minecraft without hamachi", "minecraft tunnel"],
    h1: "Hamachi Alternative for Minecraft",
    subtitle: "Built-in tunnel — dopamine",
    tag: "multiplayer",
    sections: [{ h2: "No VPN needed", paragraphs: ["Share a tunnel link — friends join without Hamachi or port forwarding."] }],
    faq: [],
    relatedSlugs: ["hamachi-alternativa-maincraft", "play-minecraft-with-friends"],
  },
  {
    slug: "play-minecraft-with-friends",
    title: "Play Minecraft with Friends | dopamine",
    description: "Play minecraft with friends: local server and tunnel in dopamine launcher.",
    keywords: ["play minecraft with friends", "minecraft multiplayer friends", "minecraft with friends pc"],
    h1: "Play Minecraft with Friends",
    subtitle: "Local server + tunnel link",
    tag: "friends",
    sections: [{ h2: "Small group multiplayer", paragraphs: ["No paid hosting — run on your PC and share the tunnel URL."] }],
    faq: [],
    relatedSlugs: ["minecraft-local-server", "server-maincraft-dlya-druzei"],
  },
  {
    slug: "minecraft-local-server",
    title: "Minecraft Local Server — dopamine",
    description: "Host minecraft local server from dopamine. RAM, slots, tunnel.",
    keywords: ["minecraft local server", "host minecraft server locally", "local minecraft server friends"],
    h1: "Minecraft Local Server",
    subtitle: "Host from your PC",
    tag: "local server",
    sections: [{ h2: "Local hosting", paragraphs: ["Same launcher as your game — same mods and version."] }],
    faq: [],
    relatedSlugs: S,
  },
  {
    slug: "best-minecraft-launcher",
    title: "Best Minecraft Launcher 2026 | dopamine",
    description: "Best minecraft launcher 2026: Modrinth, no ads, friend servers. Free Windows.",
    keywords: ["best minecraft launcher", "best minecraft launcher 2026", "top minecraft launcher"],
    h1: "Best Minecraft Launcher 2026",
    subtitle: "dopamine — mods, servers, free",
    tag: "best",
    sections: [{ h2: "Why dopamine", paragraphs: ["Modrinth, Fabric/Forge, tunnel servers, no adware — strong 2026 pick for Windows."] }],
    faq: [],
    relatedSlugs: ["luchshiy-launcher-maincraft", "free-minecraft-launcher"],
  },
  {
    slug: "alternative-minecraft-launcher",
    title: "Alternative Minecraft Launcher | dopamine",
    description: "Alternative minecraft launcher: Modrinth, servers, Fabric, Forge. Free.",
    keywords: ["alternative minecraft launcher", "third party minecraft launcher", "custom minecraft launcher"],
    h1: "Alternative Minecraft Launcher",
    subtitle: "Beyond the default Mojang client",
    tag: "alternative",
    sections: [{ h2: "When you need an alternative", paragraphs: ["Modpacks, multiple installs and friend servers — dopamine covers the workflow."] }],
    faq: [],
    relatedSlugs: ["best-minecraft-launcher", "minecraft-launcher"],
  },
  {
    slug: "custom-minecraft-launcher",
    title: "Custom Minecraft Launcher | dopamine",
    description: "Custom minecraft launcher with themes, Modrinth, profiles.",
    keywords: ["custom minecraft launcher", "minecraft launcher themes", "minecraft launcher customization"],
    h1: "Custom Minecraft Launcher",
    subtitle: "Themes and profiles",
    tag: "custom",
    sections: [{ h2: "Customize dopamine", paragraphs: ["Dark theme, per-profile RAM, Modrinth and servers built in."] }],
    faq: [],
    relatedSlugs: ["alternative-minecraft-launcher", "minecraft-launcher"],
  },
  {
    slug: "minecraft-java-launcher",
    title: "Minecraft Java Launcher | dopamine",
    description: "Minecraft Java Edition launcher. Temurin Java, Fabric, Forge.",
    keywords: ["minecraft java launcher", "minecraft java edition launcher", "java minecraft launcher"],
    h1: "Minecraft Java Launcher",
    subtitle: "Java Edition on Windows",
    tag: "java",
    sections: [{ h2: "Java Edition", paragraphs: ["Auto Temurin download per profile with Fabric, Forge or vanilla."] }],
    faq: [],
    relatedSlugs: ["minecraft-launcher-windows", "minecraft-launcher"],
  },
  {
    slug: "russkiy-launcher-maincraft",
    title: "Русский лаунчер майнкрафт | dopamine",
    description: "Русский лаунчер майнкрафт: RU/EN, Modrinth, серверы. Бесплатно.",
    keywords: ["русский лаунчер майнкрафт", "лаунчер на русском", "minecraft launcher russian"],
    h1: "Русский лаунчер майнкрафт",
    subtitle: "dopamine — RU/EN интерфейс",
    tag: "русский",
    sections: [{ h2: "Лаунчер на русском", paragraphs: ["Локализованный UI, Modrinth, аккаунт dopamine.cfd."] }],
    faq: [{ q: "English?", a: "Yes, RU/EN in settings." }],
    relatedSlugs: ["launcher-minecraft", "dopamine-launcher"],
  },
  {
    slug: "doafamin-launcher",
    title: "Дофамин лаунчер — dopamine Minecraft launcher",
    description: "Дофамин лаунчер: официальный dopamine для Windows. www.dopamine.cfd",
    keywords: ["дофамин лаунчер", "лаунчер дофамин скачать", "dopamine дофамин", "дофамин minecraft"],
    h1: "Дофамин лаунчер — dopamine",
    subtitle: "Официальный Minecraft launcher",
    tag: "дофамин",
    sections: [{ h2: "dopamine = дофамин", paragraphs: ["Скачивайте только с www.dopamine.cfd."] }],
    faq: [{ q: "Где скачать?", a: "/download на dopamine.cfd." }],
    relatedSlugs: D,
  },
  {
    slug: "maincraft-2026",
    title: "Майнкрафт 2026 — лаунчер | dopamine",
    description: "Майнкрафт 2026: dopamine — версии, Modrinth, серверы. Windows.",
    keywords: ["майнкрафт 2026", "minecraft 2026", "лаунчер майнкрафт 2026"],
    h1: "Майнкрафт 2026 — dopamine",
    subtitle: "Актуальные версии и моды",
    tag: "2026",
    sections: [{ h2: "Minecraft 2026", paragraphs: ["dopamine обновляется автоматически — Modrinth и серверы для друзей."] }],
    faq: [],
    relatedSlugs: ["minecraft", "launcher-minecraft"],
  },
  {
    slug: "podnyat-server-maincraft",
    title: "Поднять сервер майнкрафт | dopamine",
    description: "Как поднять сервер майнкрафт: локально в dopamine, туннель, без VPS.",
    keywords: ["поднять сервер майнкрафт", "запустить сервер майнкрафт", "открыть сервер minecraft"],
    h1: "Поднять сервер майнкрафт",
    subtitle: "Без хостинга — dopamine",
    tag: "сервер",
    sections: [{ h2: "Быстрый старт", paragraphs: ["Локальный сервер + ссылка друзьям через туннель."] }],
    faq: [],
    relatedSlugs: S,
  },
  {
    slug: "minecraft-launcher-no-ads",
    title: "Minecraft Launcher No Ads | dopamine",
    description: "Minecraft launcher no ads — free, clean, Modrinth, servers.",
    keywords: ["minecraft launcher no ads", "ad free minecraft launcher", "clean minecraft launcher"],
    h1: "Minecraft Launcher — No Ads",
    subtitle: "Free without adware",
    tag: "no ads",
    sections: [{ h2: "Clean launcher", paragraphs: ["dopamine is free without banners or bundled junk."] }],
    faq: [],
    relatedSlugs: ["free-minecraft-launcher", "best-minecraft-launcher"],
  },
  {
    slug: "igra-maincraft",
    title: "Игра майнкрафт на ПК | dopamine",
    description: "Игра майнкрафт: dopamine launcher — моды, сервер, Windows.",
    keywords: ["игра майнкрафт", "играть в майнкрафт", "игра minecraft на пк"],
    h1: "Игра майнкрафт — dopamine",
    subtitle: "Запуск, моды, мультиплеер",
    tag: "игра",
    sections: [{ h2: "Играть на ПК", paragraphs: ["Версии, Java, Modrinth и сервер — в одном лаунчере."] }],
    faq: [],
    relatedSlugs: ["maincraft-na-pk", "minecraft", "launcher-minecraft"],
  },
];
