/** Глобальные keywords для meta-тегов сайта */
export const GLOBAL_SEO_KEYWORDS = [
  // EN — launcher
  "minecraft launcher",
  "minecraft launcher download",
  "free minecraft launcher",
  "best minecraft launcher",
  "minecraft launcher windows",
  "minecraft launcher windows 10",
  "minecraft launcher windows 11",
  "minecraft launcher with mods",
  "minecraft launcher pc",
  "custom minecraft launcher",
  "alternative minecraft launcher",
  "minecraft java launcher",
  "minecraft java edition launcher",
  "minecraft modpack launcher",
  "minecraft multiplayer launcher",
  "minecraft launcher no ads",
  "minecraft launcher 2026",
  "dopamine minecraft launcher",
  "dopamine launcher",
  "dopamine launcher download",
  // EN — mods
  "fabric launcher",
  "forge launcher",
  "neoforge launcher",
  "modrinth launcher",
  "modrinth modpack launcher",
  "minecraft fabric launcher",
  "minecraft forge launcher",
  // EN — servers
  "minecraft server",
  "minecraft servers",
  "create minecraft server",
  "minecraft server for friends",
  "minecraft local server",
  "play minecraft with friends",
  "minecraft multiplayer friends",
  "hamachi alternative minecraft",
  "minecraft server without port forwarding",
  // EN — brand
  "dopamine",
  "dopamine.cfd",
  "dopamine minecraft",
  // RU — launcher
  "лаунчер майнкрафт",
  "майнкрафт лаунчер",
  "лаунчер minecraft",
  "лаунчер майнкрафт скачать",
  "скачать лаунчер майнкрафт",
  "скачать лаунчер minecraft",
  "лаунчер майнкрафт бесплатно",
  "лучший лаунчер майнкрафт",
  "лаунчер майнкрафт на пк",
  "лаунчер майнкрафт windows",
  "лаунчер minecraft windows",
  "minecraft launcher скачать",
  "русский лаунчер майнкрафт",
  "лаунчер с модами",
  "лаунчер с модами майнкрафт",
  "лаунчер minecraft с модами",
  // RU — game
  "майнкрафт",
  "minecraft",
  "скачать майнкрафт",
  "майнкрафт на пк",
  "майнкрафт на компьютер",
  "игра майнкрафт",
  "майнкрафт с модами",
  "майнкрафт бесплатно",
  "майнкрафт 2026",
  // RU — brand
  "дофамин",
  "дофамин лаунчер",
  "лаунчер дофамин",
  "майнкрафт дофамин",
  "dopamine майнкрафт",
  // RU — mods
  "fabric майнкрафт",
  "forge майнкрафт",
  "neoforge майнкрафт",
  "modrinth майнкрафт",
  "modpack майнкрафт",
  "сборки майнкрафт",
  // RU — servers
  "создать сервер майнкрафт",
  "как создать сервер майнкрафт",
  "сервер майнкрафт",
  "майнкрафт серверы",
  "сервер майнкрафт для друзей",
  "локальный сервер майнкрафт",
  "играть с друзьями майнкрафт",
  "майнкрафт с друзьями",
  "хамachi альтернатива майнкрафт",
  "hamachi майнкрафт альтернатива",
  "сервер minecraft для друзей",
  "поднять сервер майнкрафт",
] as const;

export const BRAND_ALTERNATE_NAMES = [
  "dopamine Minecraft launcher",
  "dopamine minecraft launcher",
  "dopamine launcher",
  "dopamine лаунчер",
  "dopamine лаунчер майнкрафт",
  "дофамин",
  "дофамин лаунчер",
  "лаунчер дофамин",
  "майнкрафт дофамин",
  "дофамин майнкрафт",
  "лаунчер майнкрафт dopamine",
  "майнкрафт лаунчер dopamine",
  "dopamine minecraft",
  "dopamine.cfd launcher",
] as const;
